on:
  schedule:
    - cron:  '35 4 * * 6'
    
  workflow_dispatch:

name: test-generate-translations

jobs:
  test-generate-translations:
    runs-on: ubuntu-latest
    env:
      REPO_KEY: ${{ secrets.REPOS_KEY }}
      WEBLATE_KEY: "HOI" #${{ secrets.WEBLATE_KEY }}
      QML_REPO: jaspacceptancesampling-qml
      R_REPO: jaspacceptancesampling-r
      
    steps:
      - uses: jasp-stats/jasp-actions/wlcLock@testWeblate
      
      #- uses: jasp-stats/jasp-actions/translations@master
